# Generated by Django 4.1 on 2024-01-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.IntegerField()),
                ("sname", models.CharField(max_length=60)),
                ("smark", models.FloatField()),
                ("saddr", models.CharField(max_length=250)),
            ],
        ),
    ]
